---
title: "Rtest_210316"
author: "ae"
date: "2021/3/16"
output: word_document
---

## 创建向量
```{r}
x1=c(171,175,159,155,152,158,154,164,168,166,159,164)
x2=c(57,64,41,38,35,44,41,51,57 ,49,47,46)
```

## 将向量按列和并
```{r}
rbind(x1,x2)
```

## 利用x1数据创建矩阵
```{r}
matrix(x1,nrow=3,ncol=4)
```

## 创建按照行排列的矩阵
```{r}
matrix(x1,nrow=3,ncol=4,byrow=T)
```

## 创建两个相同的矩阵
```{r}
A=B=matrix(1:12,nrow=3,ncol=4)
A;B
```

## 矩阵转置
```{r}
t(A)  
```

## 矩阵加法
```{r}
A+B 
```

## 矩阵减法
```{r}
A-B 
```

## 矩阵相乘
```{r}
A=matrix(1:12,nrow=3,ncol=4) 
B=matrix(1:12,nrow=4,ncol=3)
A%*%B
```

## 获取对角线元素
```{r}
A=matrix(1:16,nrow=4,ncol=4)
diag(A) 
```

#利用对角线元素创建对角矩阵
```{r}
diag(diag(A))
```

## 创建3阶单位矩阵
```{r}
diag(3)
```

## 求逆矩阵
```{r}
A=matrix(rnorm(16),4,4)
solve(A)
```

## 求矩阵特征根与特征向量
```{r}
A=diag(4)+1
A.e=eigen(A,symmetric=T)
A.e
```


## 矩阵的Choleskey分解
```{r}
A.c=chol(A)
A.c
```

## 矩阵奇异值分解
```{r}
A=matrix(1:18,3,6)
A.s=svd(A)
A.s
```

## 矩阵的维数
```{r}
A=matrix(1:12,3,4)
dim(A)
```

## 矩阵的行数
```{r}
nrow(A)
```

#矩阵的行数
```{r}
ncol(A)
```

## 矩阵按行求和
```{r}
rowSums(A)
```

## 矩阵按行求均值
```{r}
rowMeans(A)
```

## 矩阵按列求和
```{r}
colSums(A)
```

## 矩阵按列求均值
```{r}
colMeans(A)
```

## 矩阵按行求和
```{r}
apply(A,1,sum)
```

## 矩阵按行求均值
```{r}
apply(A,1,mean)
```

## 矩阵按列求和
```{r}
apply(A,2,sum)
```

## 矩阵按列求均值
```{r}
apply(A,2,mean)
```

## 矩阵按列求方差
```{r}
A=matrix(rnorm(100),20,5)
apply(A,2,var)
```

## 矩阵按列求函数结果
```{r}
B=matrix(1:12,3,4)
apply(B,2,function(x,a) x*a, a=2)
```

## 由x1和x2构建数据框
```{r}
X=data.frame(x1,x2)
X
```

## 赋予数据框新的列标签
```{r}
X=data.frame('身高'=x1,'体重'=x2)
X
```

## 读取名为textdata的txt格式文档
```{r}
X=read.table("./textdata.txt")
X
```

## 身高的直方图
```{r}
hist(x1)
```

## 身高与体重散点图
```{r}
plot(x1,x2)
```
## 读取csv格式和excel格式 pass
```{r}
library(readxl)
X=read_excel("./msaD.xlsx")
X
library(openxlsx)
X=read.csv("./test1.csv")
X
```

```{r}
#将剪切板数据读入数据框d2.1中
d2.1=read.table("clipboard",header=T)
str(d2.1)
#显示数据前6行
# head(d2.1)
```

```{r}
#绑定数据
attach(d2.1)
#一维列联表
table(年龄)
```


```{r}
#条形图
barplot(table(年龄),col=1:7)
```

```{r}
#饼图
pie(table(结果))

```

```{r}
#以性别分组的年龄条图
barplot(table(年龄,性别),beside=T, col=1:7)
```

```{r}
#以年龄分组的性别条图
barplot(table(性别,年龄),beside=T,col=1:2)
```

```{r}
#以年龄、性别排列的结果频数三维列联表
ftable(年龄,性别,结果)
```


```{r}
#以性别、年龄排列的结果频数三维列联表
ftable(性别,年龄,结果)
```


```{r}
ft=ftable(性别,结果,年龄)
ft
```

```{r}
#求ft的行和
rowSums(ft)
```

```{r}
#求ft的列和
colSums(ft)
```

## 解除绑定！！
```{r}
detach(d2.1)
```

##案例2多元数据的基本统计分析##
```{r}
Case2=read.xlsx('./mvcase5.xlsx','Case2');head(Case2)
summary(Case2)
T1= table(Case2$地区);T1
barplot(T1, col=1: 4)
f=hist(Case2$月收入);f
boxplot(月收入~性别,Case2)
t.test(月收入~性别,Case2)
T2= table(Case2$性别,Case2$观点);T2
barplot(T2, beside=T, horiz =T, col=1: 2)
T3= ftable(Case2$性别,Case2$教育程度,Case2$观点);T3
barplot(T3, beside =T, col=1: 3)
T4= ftable(Case2$教育程度,Case2$性别,Case2$观点);T4
barplot(T4, beside=T, col=1: 3)
```



















